spring:
  main:
    banner-mode: off
    web-application-type: none
  application:
    name: migration
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/test}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
      auto-commit: false
  liquibase:
    default-schema: ${POSTGRES_SCHEMA:test}
    change-log: classpath:/${POSTGRES_SCHEMA:test}/master.yml
    database-change-log-table: _databasechangelog
    database-change-log-lock-table: _databasechangeloglock