server:
  port: ${SERVER_PORT:8080}
spring:
  main:
    banner-mode: off
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/auc}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      auto-commit: false
  jpa:
    show-sql: ${SHOW_SQL:false}
    database: postgresql
    #hibernate:
      #ddl-auto: validate TODO:раскомментить как будут миграции
    properties:
      hibernate.default_schema: gateway


auth:
  expirationMillis: 900000
  refreshExpirationMillis: 3600000
  secretKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  permitall:
    - "/"
    - "/login**"
    - "/callback/"
    - "/webjars/**"
    - "/error**"
    - "/api/auth/**"
    - "/api/swagger-ui/**"
